version: '3'
services:
  api:
    build: .

  relay:
    build:
      dockerfile: Dockerfile.relay
      context: .
    environment:
      RELAY_HOST: api
      RELAY_PORT: 8000
      PORT: 8001
    ports:
      - "8001:8001"
